repos:
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff
        files: synphage/
        language_version: python3.11

  - repo: local
    hooks:
      - id: radon-cyclomatic-complexity
        language: system
        name: Radon Cyclomatic Complexity
        entry: uv run radon cc --min C synphage