name: ci 
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
    - name: Setup ncbi-blast+
      run: |
        sudo apt update
        sudo apt install ncbi-blast+ -y
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Generate coverage report
      run: |
        pip install --upgrade pip
        pip install '.[test]'
        coverage run -m pytest test/unit
        coverage xml -o coverage.xml
      env:
        PHAGY_DIRECTORY: ${{ env.PHAGY_DIRECTORY }}
        FILE_SYSTEM: ${{ env.FILE_SYSTEM }}
        EMAIL: ${{ secrets.EMAIL }}
        API_KEY: ${{ secrets.API_KEY }}